[package]
name = "flight-booking"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "src/utils", ".", "migration"
]

[[bin]]
name = "flight-booking"
path = "src/bin/main.rs"

[workspace.dependencies]
utils = { path = "src/utils" }

[dependencies]
migration = { path = "migration" }
utils = {path = "src/utils"}

# --- ğŸŒ Web Framework & Routing ---
axum = "0.8.3"

axum-extra = { version = "0.10.1", features = ["query", "typed-header", "multipart"] }
tokio = { version = "1.42.0", features = ["full"] }
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.2", features = ["compression-full", "cors", "full"] }

# --- ğŸ“˜ OpenAPI / Swagger UI ---
utoipa = { version = "5.2.0", features = ["axum_extras", "uuid", "chrono"] }
utoipa-axum = "0.2.0"
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }

# --- ğŸ›¡ï¸ Auth, Security ---
argon2 = "0.5.3"
jsonwebtoken = { version = "10.1.0", features = ["rust_crypto"] }
validator = { version = "0.20.0", features = ["derive"] }

# --- ğŸ—„ï¸ Database / ORM ---
sqlx = { version = "=0.6.3", features = ["runtime-tokio-rustls", "postgres"] }
sea-orm = { version = "2.0.0-rc.19", features = ["sqlx-postgres", "runtime-tokio-rustls", "debug-print", "macros"] }
sea-orm-migration = { version = "=2.0.0-rc.20", features = ["default"] }

# --- ğŸ§  Redis Client ---
redis = { version = "1.0.0", features = ["tokio-comp", "connection-manager"] }

# --- ğŸ§° Utilities, Errors, Traits ---
anyhow = "1.0.94"
async-trait = "0.1.83"
config = "0.15.0"
error-stack = "0.4.1"
thiserror = "1.0.69"
once_cell = "1.21.1"
uuid = "1.11.0"
futures = "0.3.30"
bytes = "1.9.0"

# --- ğŸ“Š Logging / Tracing ---
log = "0.4.14"
env_logger = "0.11.7"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

# --- ğŸ§ª JSON, Serialize / Deserialize ---
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_urlencoded = "0.7.1"
serde_with = "3.12.0"

# --- ğŸ“… Time, Date, String tools ---
chrono = { version = "0.4.39", features = ["serde"] }
chrono-tz = "0.10.4"
strum = { version = "0.26.3", features = ["derive", "strum_macros"] }

# --- ğŸŒ HTTP Client ---
reqwest = { version = "0.12.9", features = ["json"] }
axum-reverse-proxy = "1.0.3"
rand = "0.8.5"
sea-query = "0.32.3"
regex = "1.11.1"
dotenv = "0.15.0"

rdkafka = "0.38.0"
rust_decimal = "1.39.0"
[dependencies.rdkafka-sys]
version = "4.9.0"
features = ["cmake-build"]

[build-dependencies]
tonic-build = "0.13.1"
