profile = "local"
[server]
addr = "127.0.0.1"
port = 3001

[db]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "Bxk180621"
database_name = "june18-user-service"
max_connections = 50
database_url = "postgres://postgres:Bxk180621@localhost:5432/june18-user-service"

[sentry]
dsn = ""

[secret]
private_access_key = "/static/secret_key/private_access_rsa_key.pem"
public_access_key = "/static/secret_key/public_access_rsa_key.pem"
private_refresh_key = "/static/secret_key/private_refresh_rsa_key.pem"
public_refresh_key = "/static/secret_key/public_refresh_rsa_key.pem"

[redis]
username = "default"
password = "HEeQ5Sx9OlV7SMBImXFT9yIFA7pBNkhO"
host = "localhost"
port = 6379
database_name = "0"


[http]
timeout = 1000000

[kafka]
server_url = ""
timeout_ms = ""
allow_auto_create_topics = ""
enable_auto_commit = ""

[[gateway.services]]
name = "product-service"
base_url = "http://localhost:3002"
health_check_path = "/health"
timeout_secs = 30
require_auth = true

deploy_mode = "mono"